python Tuning_LASSO.py O fasttext ../FastText/dataset.vec yes
python Tuning_LASSO.py C fasttext ../FastText/dataset.vec yes
python Tuning_LASSO.py E fasttext ../FastText/dataset.vec yes
python Tuning_LASSO.py A fasttext ../FastText/dataset.vec yes
python Tuning_LASSO.py N fasttext ../FastText/dataset.vec yes
python Tuning_SVM.py O fasttext ../FastText/dataset.vec yes
python Tuning_SVM.py C fasttext ../FastText/dataset.vec yes
python Tuning_SVM.py E fasttext ../FastText/dataset.vec yes
python Tuning_SVM.py A fasttext ../FastText/dataset.vec yes
python Tuning_SVM.py N fasttext ../FastText/dataset.vec yes
